version: "3"

services:
  app:
    image: ros-melodic-with-calibration-and-rosbags:latest
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../rosbags:/root/LaserCameraCal_ws/src/CamLaserCalibraTool/rosbags/
      - ../logs:/root/LaserCameraCal_ws/src/CamLaserCalibraTool/logs/
    network_mode: host
