version: "3"

services:
  app:
    image: ros-melodic-with-camlasercalibration:latest
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host